### ISSUE TITLE
Router: No matching caller for invocation

### ISSUE THREAD

**Issue by johannwagner** [gammazero/nexus#114]
Hey, 

I just ran into a bug, where the invocation of a function does *not* work in the first time, but works fine afterwards. 

Nexus logs: `2018/06/23 14:31:51 !!! No matching caller for invocation from YIELD: 16`
[Entire Logfile](https://gitlab.ci.server.creatdev-solutions.com/snippets/5)

I thought it is maybe an error, because the client dies, but the client seems fine. I use [wampy.js](https://github.com/KSDaemon/wampy.js) as my client lib. 

If you have additional questions, don't be afraid to ask.

Best Regards, Johann

**Comment by gammazero** [comment]
I want to fix any bug ASAP.  Do  you have a test to reproduce, or can you modify any of the existing test in `aat/`, maybe `aat/rpc_test.go` to show the problem?

**Comment by gammazero** [comment]
I think I see the problem:  There are two CALL messages each submitted with the same Request ID (3 in the log).  The first YIELD that received deletes the mapping from Request ID to pending call:
https://github.com/gammazero/nexus/blob/master/router/dealer.go#L752-L753

The the second YIELD no longer has a mapping for Request ID 3.  This look like a bug in the client, as the Request ID should be different for each request.
https://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#call-1

"Request is a random, ephemeral ID chosen by the Caller and used to correlate the Dealer's response with the request."

In your case the YIELD to the second CALL is received first, which is why it looks like the first CALL fails.

**Comment by johannwagner** [comment]
Thanks a lot for the quick fix. Works like a charm!
