### ISSUE TITLE
anonymous connect nexus server returned error

### ISSUE THREAD

**Issue by goldcode88** [gammazero/nexus#126]
The following code runs successful in crossbar.io. But when I connected to nexus server, server returned error.
"2018/07/08 18:08:33 Error upgrading to websocket connection: websocket: request origin not allowed by Upgrader.CheckOrigin
2018/07/08 18:08:33 http: multiple response.WriteHeader calls"

Authbahn js client receives "failed: Error during WebSocket handshake: Unexpected response code: 403".

```
const wsuri = "ws://xx.xxx.com:8901/ws";
const connection = new autobahn.Connection({
        url: wsuri,
        realm: "realm",
        authmethods: ["anonymous"],
    });
connection.open()

nexus config.json:
{
    "websocket": {
        "address": "xx.xxx.com:8901",
        "cert_file": "",
        "key_file": "",
        "enable_compression": false,
        "allow_origins": ["xx.xxx.com"]
    },
    "rawsocket": {
        "tcp_address": "",
        "tcp_keepalive_interval": 180,
        "unix_address": "",
        "max_msg_len": 0,
        "cert_file": "",
        "key_file": ""
    },
    "log_path": "",
    "router": {
        "realms": [{
            "uri": "realm",
            "strict_uri": false,
            "allow_disclose": true,
            "anonymous_auth": true,
            "meta_strict": false,
            "meta_include_session_details": [],
            "enable_meta_kill": false,
            "enable_meta_modify": false
        }],
        "debug": false
    }
}

crossbar.io config.json:
"realms": [{
            "name": "realm",
            "roles": [{
                "name": "public",
                "permissions": [{
                    "uri": "user.login.authenticate",
                    "match": "prefix",
                    "allow": {
                        "call": true,
                        "register": true,
                        "publish": true,
                        "subscribe": true
                    },
                    "disclose": {
                        "caller": false,
                        "publisher": false
                    },
                    "cache": true
                }]
            }]
        }]
... ...
"transports": [{
            "type": "universal",
            "endpoint": {
                "type": "tcp",
                "port": 8901
            },
            "rawsocket": {},
            "websocket": {
                "ws": {
                        "auth": {
                            "anonymous": {
                                  "type": "static",
                                  "role": "public"
                        }
            }
}



```

**Comment by goldcode88** [comment]
I have solved it.
In nexus config.json. Modified "allow_origins": ["xx.xxx.com"]  into "allow_origins": ["xx.xxx.com:8900"].
Login on "http://xx.xxx.com:8900" in Browser. It returns ok. 
In "vendor/github.com/gorilla/websocket/server.go", function checkSameOrigin(...).

```
func checkSameOrigin(r *http.Request) bool {
	origin := r.Header["Origin"]                // origin == "http://xx.xxx.com:8900"
	if len(origin) == 0 {
		return true
	}
	u, err := url.Parse(origin[0])              // u.origin == "http://xx.xxx.com:8901"
	if err != nil {
		return false
	}
	return equalASCIIFold(u.Host, r.Host)  // u.Host == "http://xx.xxx.com:8900"
                                                                         // r.Host  == "http://xx.xxx.com:8901"
                                                                         // u.Host =/= r.Host, return false
}

```
So if we set  "allow_origins": ["xx.xxx.com"] or [], nexus will execute checkSameOrigin. It always returns false. When client connects to nexus server, server will return error in Upgrader.CheckOrigin.

I think It a choice in func AllowOrigins(nexusd/wsutil/alloworigins.go) ignore port, only check hostname.

**Comment by gammazero** [comment]
What I have seen in other router implementations using nexus, is to match _any_ origin if support of CORS is enabled.  That is done by supplying a function that returns `true` regardless of origin.  If using `wsutil` the same can be done by specifying `["*"]`.

If you do want to limit to certain specified origins, but have a port in the URI, one thing you can do now is specify a wildcard for the port: `["*.somewhere.com:*"]`.

I think what you are looking for is a new API so that you can call like this:
```
check, err := AllowOriginsWithPorts(origins []string, ports []int)
````
If `ports` is nil or empty, then ignore the port part of the URI when matching.  Otherwise, match the specified ports.  Do we need port ranges?  Let me know if this is what you need and I will provide this functionality, or if a wildcard port is OK I can leave it.

I chose to put `wsutil` under `nexusd/` because I was not sure if that matching implementation would be generally useful, and implementors would provide their own matching logic.  If this is generally useful, maybe it makes sense to move the `wsutil` package out of the `nexusd/` and into `router/`.  Thoughts?

**Comment by goldcode88** [comment]
Thanks! 
I think ["*.somewhere.com:*"] is ok.  "port ranges" is not necessary.

About wsutil, nexus(current version) seems only support one router(one worker process). In this case, putting wsutil under nexusd is ok. One router is enough in most of scenarios.
If nexus has a plan to support multiple workers model, wsutil should be put into router/.
Multiple workers' model I thought is from crossbar's model. Like this.

```
{
    "version": 2,
    "controller": {},
    "workers": [{
        "type": "router",
        "realms": [{
            "name": "realm1",
            //... ...
        }, {
            "name": "realm2",
            //... ...
        }],
        "transports": [{
            "type": "universal",
            "rawsocket": {
                // ... ...
            },
            "websocket": {
                "address": "xx.xxx.com:8901",
                // ... ...
            }
        }]
    }, {
        "type": "router",
        "realms": [{
            "name": "realm1",
            //... ...
        }, {
            "name": "realm2",
            //... ...
        }],
        "transports": [{
            "type": "universal",
            "rawsocket": {
                // ... ...
            },
            "websocket": {
                "address": "xx.xxx.com:8902",
                // ... ...
            }
        }]
    }]
}
```

**Comment by gammazero** [comment]
Just to be clear, when I said `["*.somewhere.com:*"]`, I literally mean use the asterisk `*` wildcard character.  Using that for the port will allow _any_ port, but does not allow specification of only certain ports.

As far as multiple workers...  You are correct that each instance of nexus (each router process), only supports a single router.  However, each router supports all possible transports that you may configure, and as many realms as you configure.  Each realm within a router runs completely concurrently to all other realms - meaning that each realm's broker and dealer run concurrently to all other realm's broker and dealer, and all each client message handler runs concurrently from all other message handlers, even within the same realm.  If you want multiple routers, then create multiple router instances (with all the transports and realms you want for each ).  You can have as many as you like, even in the same process, as long as the transports listen on different ports.

So, the multiple workers functionality is there, just solved in a slightly different way... which basically means using separate configs for each router, instead of one big config specifying multiple workers.

Anyhow, let me know if you see a need to provide a new API to deal with ports, or anything else.

**Comment by goldcode88** [comment]
I got it. Multiple nexus instances for multiple workers is a simple and clear solution. Thanks.
About specific ports, current solution can be satisfied for most of  scenarios.
If we only concern domain name, just use ["*.somewhere.com:*"].
If we have several ports, we can list all of ports exactly.
```
["*.somewhere.com:8901", 
"*.somewhere.com:8902", 
"*.somewhere.com:8905", 
"*.somewhere.com:8908"]
```
Sometimes Port is discontinuous. So I think "port ranges" API is a user-friendly function, but it is not a requisite function.

**Comment by gammazero** [comment]
I have added comments, examples, and unit tests for origins with ports.  Here is the new documentation: https://godoc.org/github.com/gammazero/nexus/nexusd/wsutil#AllowOrigins

I am considering moving this functionality into the [`WebsockerServer`](https://godoc.org/github.com/gammazero/nexus/router#WebsocketServer)

So, instead of doing this:
```
check, err := wsutil.AllowOrigins([]string{"*.somewhere.com:8080"})
if err != nil {
    log.Fatal(err)
}
wsServer.Upgrader.CheckOrigin = check
```
Code would be this:
```
wsServer.AllowOrigins([]string{"*.somewhere.com:8080"})
if err != nil {
    log.Fatal(err)
}
```

One could still define their own function: `wsServer.Upgrader.CheckOrigin = originChecker`.  Need to consider if this is what most people supporting CORS would want.

**Comment by goldcode88** [comment]
From my understand, the new implementation is like this.

```
err := wsServer.AllowOrigins([]string{"*.somewhere.com:8080"})
if err != nil {
    log.Fatal(err)
}

func AllowOrigins(...) {
      s.Upgrader.CheckOrigin = func(r *http.Request) bool {
		return checkOrigin(exacts, globs, r)
	}
}

func checkOrigin() {
... ...
}

```

From my opinion, It's no different on CORS feature for websocket between the new and the old implementation. Maybe I misunderstand your mean.

**Comment by gammazero** [comment]
I have not changed the implementation.  I was asking if would be easier to have the `AllowOrigins()` be a method of `WebsocketServer` or if `AllowOrigins` should remain in a separate package (`wsutil`).

**Comment by goldcode88** [comment]
Got it. I prefer to moving this `AllowOrigins()` into the `WebsockerServer`.
