### ISSUE TITLE
Event History implementation.

### ISSUE THREAD

**Issue by alessandro-c** [gammazero/nexus#240]
Hello 👋 and thank you for maintaining this repository.

Is there any plan to implement a persistent [Event History](https://wamp-proto.org/_static/gen/wamp_latest.html#event-history) any time soon?

Thanks in advance

**Comment by gammazero** [comment]
Yes, planning on doing that.  Need to get one point of clarification to the WAMP spec first:
https://github.com/wamp-proto/wamp-proto/issues/217#issuecomment-749750503

Otherwise, the plan is to have implementation equivalent to what Crossbar provides:
https://crossbar.io/docs/Event-History/#event-history
