### ISSUE TITLE
Using wamp.Dict for args instead of Wamp.List

### ISSUE THREAD

**Issue by markusbkk** [gammazero/nexus#275]
I'm fairly new to this library.
While I understand the basic premise, I fail to properly deserialize arguments on the callee's end.

My caller invokes the RPC function with the following args:

```go
type Hello struct {
	Name       string `json:"name"`
	Salutation string `json:"salutation"`
}

func Test (c *Hello) {
  client, err := client.NewNetClient(log.Default())
  if err != nil {
    log.Fatal(err)
   }
  defer client.Close()

  callArgs := wamp.List{Hello{Name: c.Name, Salutation: c.Salutation}}
  ctx := context.Background()
  _, err = client.Call(ctx, "gen_pdf", nil, callArgs, nil, nil)
  if err != nil {
    log.Fatal(err)
  }
```

On the callee side I run the following

```go
func GeneratePDF(ctx context.Context, inv *wamp.Invocation) client.InvokeResult {
  fmt.Println(inv.Arguments)

  results := wamp.List(nil)
  return client.InvokeResult{Args: results}
}
```

Where it says ``fmt.Println(inv.Arguments)``, how can I properly deseralize this (from its current ``[map[name:Tester salutation:Mr]]``) so I can access the invocation arguments as fields?

**Comment by KSDaemon** [comment]
Hi @markusbkk well, there is nothing wrong here with the arguments themselves. You just need to treat/convert your Arguments[0] to Hello struct. There are different approaches for this: manually, using reflection, or some external packages. Choose what suits best for you.

Just googling for you: 
* https://stackoverflow.com/questions/26744873/converting-map-to-struct
* https://stackoverflow.com/questions/48994008/mapstringinterface-to-struct-with-json-tags

And btw, if you want to pass a single hashmap-like object - why not to pass it as ArgumentsKw instead of Arguments? :)
