### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by koliyo** [gammazero/nexus#70]
Have you considered implementing compression?

https://crossbar.io/docs/WebSocket-Compression/

**Comment by gammazero** [comment]
Yes.  Nexus uses [gorilla/websocket](https://github.com/gorilla/websocket), so compression support would be provided by that package.   It is currently marked as [experimental](https://godoc.org/github.com/gorilla/websocket#hdr-Compression_EXPERIMENTAL), and only appears to allow compression to be enabled or disabled.

I will expose a configuration option, for the server and for the client, to enable compression.  If more options become available in gorilla/websocket, I can surface them in router and client config.

**Comment by gammazero** [comment]
I have exposed options in both the server and client to enable compression.  This is all available in PR #77 .  After doing Pub/Sub benchmarks, enabling compression is significantly slower, at least for small messages.

WAMP messages are generally small, and therefore see little or no benefit from compression.  Enabling websocket compression for all client or server messages will generally decrease performance, unless most of the messages are large enough to benefit from compression, which would be unusual for most WAMP uses.  It is therefore recommended for applications using WAMP to compress their own large message payloads, or use WAMP to communicate an endpoint that can serve bulk data more efficiently, instead of relying on websocket compression.

Given that, I am not sure if it is worth even allowing websocket compression to be enabled over WAMP.  Try out the [compression branch](https://github.com/gammazero/nexus/tree/compression) and let me know if you still think nexus should support websocket compression.

**Comment by gammazero** [comment]
Fixed by merged PR #77.
