### ISSUE TITLE
Private Subscription

### ISSUE THREAD

**Issue by l-vitaly** [gammazero/nexus#76]
It is necessary to have a subscription that can be read by one, can this be done somehow?

**Comment by gammazero** [comment]
Do you mean to have the router limit the number of subscribers to a topic, in this case to 1?  There is not a setting to limit the number of subscribers, however, I am not sure if this is what you really need.

Publishers do have some ability to determine which specific subscribers to publish events to:
https://github.com/gammazero/nexus/wiki/Extended-Functionality

You can also exclude clients using auth/authz, but not sure that helps you.  Maybe you can give more detail on the problem you are trying to solve.

**Comment by gammazero** [comment]
I am closing this issue, because I believe that what you are asking for can be accomplished by defining an authorizer that only allows a particular session (has specific authid or authrole) to subscribe to a topic.  

This means implementing an [authorizer](https://godoc.org/github.com/gammazero/nexus/router#Authorizer) and providing it in the [realm config](https://godoc.org/github.com/gammazero/nexus/router#RealmConfig) when configuring the router.  The authorizer will allow the router to make per-message decisions by looking at the receiving session and the message.  In your case, the authorizer will look see if the message is a subscription, maybe to a certain topic, and then see if the session requesting the subscription is the correct session.

See here for more information and example: https://github.com/gammazero/nexus/wiki/Authorizer

If the publisher needs to decide whether or not to publish a message to certain session, subscriber black/white listing can be used for this. See here for details: https://godoc.org/github.com/gammazero/nexus/client#hdr-Options
