### ISSUE TITLE
Compatibility between Nexus and Angular 5 using AutobahnJS

### ISSUE THREAD

**Issue by robfra31** [gammazero/nexus#93]
Hello,
Did you ever heard about someone trying to use Nexus server with Angular 5 and AutobahnJS library ?
I tried and had some problems:
- From front (Angular app) I have the error: WebSocket connection to 'ws://localhost:8080/ws' failed: Error during WebSocket handshake: Unexpected response code: 403
- From back (Nexus server) I have the error: 2018/04/04 10:12:22 http: multiple response.WriteHeader calls
2018/04/04 10:12:30 Error upgrading to websocket connection: websocket: 'Origin' header value not allowed
Does anyone have an idea ?

Regards,

**Comment by gammazero** [comment]
I have not had any other reports of this, and I have used nexus with Autobahn Python.  Have not tested with Angular 5.  Nexus uses the [gorilla websocket](ttps://github.com/gorilla/websocket) implementation, so perhaps there is an issue there as that handles the websocket handshake.

I will look into it.  This may offer some info: https://www.reddit.com/r/golang/comments/2j0v46/the_origin_not_allowed_error/

**Comment by gammazero** [comment]
Nexus is using the default Upgrader behavior for handling the origin header from the websocket upgrade request.  The behavior is documented here:
https://godoc.org/github.com/gorilla/websocket#Upgrader
```
// CheckOrigin returns true if the request Origin header is acceptable. If
// CheckOrigin is nil, then a safe default is used: return false if the
// Origin request header is present and the origin host is not equal to
// request Host header.
```
So, it appears that in your case the origin host != request host.

There is currently no way to specify your own `CheckOrigin` function to the nexus router, so looks like I should add this feature.

**Comment by robfra31** [comment]
It is not possible to directly define this when creating the Nexus server via the nexus.json file ?

**Comment by gammazero** [comment]
nexus does not supply an implementation of `CheckOrigin`, so that is something a router implementer would currently need to supply.

So, realizing that is something that may be needed in nexusd, I could provide an implementation and allow it to be configured via JSON config. It would only be able to do basics, like allowing from a list of origins, or origin patterns.  Otherwise, I would be making too many guesses about what the user needed.   Any other suggestions?

I am not sure if this would be useful in router library, since an implementer could easily supply their own function.  Would this be something you would use in the nexus router library, or only need it in the nexusd executable?

**Comment by gammazero** [comment]
Here is what I am considering as a solution.  I will add a function to the WebsocketServer that can be used to allow origins that match any of the glob patterns given:
```go
// AllowOrigin sets the WebsocketServer.Upgrader.CheckOrigin to a function that
// returns true if: the origin is not set, is equal to the request host, or     
// matches one of the allowed patterns.  A pattern is in the form of a shell    
// glob as described here: https://golang.org/pkg/path/filepath/#Match          
func (s *WebsocketServer) AllowOrigins(patterns []string) error { ... }
```
In nexusd config JSON you can specify:
```json
{
    "websocket": {
        "allow_origins": ["*.foo.com", "*.bar.*"]
    },
...
}
```
If you want to try this out, it is in the branch: https://github.com/gammazero/nexus/tree/serverconfig
Does this seem to do what you need?

**Comment by gammazero** [comment]
I have moved the code to allow origins into the nexusd code, in `wsutil`, since that is only one of innumerable possible ways someone may want to implement a CheckOrigin function.  Maybe they would rather query a local DNS, or database, etc., so best to let implementor provide this.  The code can still be used in a custom implementation as if it is useful.

**Comment by gammazero** [comment]
I have not tried the AutobahnCpp lib yet.  Nexus should produce logs about any client errors.  Here are some samples:

```
2018/04/10 11:27:28 Error attaching to router: no realm "nexus.realm1" exists on this router
```
```
2018/04/10 11:29:48 Aborting client connection: could not authenticate with any
method
```

If you enable `debug` in the realm config, then you can see more information including when a new client session is created:
https://github.com/gammazero/nexus/blob/serverconfig/nexusd/etc/nexus.json#L26

Also fixed a couple errors in above file, which may have been a problem.  Let me know if you see any problems with nexus.

**Comment by robfra31** [comment]
Hello,
So, I still can't use Nexus server with Autobahn Libraries Cpp and Java. I have added logs flag in the server config but nothing is printed.
Do you have any code example with Autobahn Cpp and Java which is working ?
Thank you very much !

**Comment by gammazero** [comment]
Can you give me a link to any code you are trying to make work.  If I could build that and debug maybe I could solve this (plus get some good interoperability testing).  Java or C++ is OK, preferably whatever is simplest code that exhibits problem.

**Comment by robfra31** [comment]
I am trying the code gave by Autobahn:
- Java (https://github.com/crossbario/autobahn-java):
`public void main() {
    // Create a session object
    Session session = new Session();
    // Add all onJoin listeners
    session.addOnJoinListener(this::demonstrateSubscribe);
    session.addOnJoinListener(this::demonstratePublish);

    // finally, provide everything to a Client and connect
    Client client = new Client(session, url, realm);
    CompletableFuture<ExitInfo> exitInfoCompletableFuture = client.connect();
}`
This is for the connection, and the procedure are:
`public void demonstrateSubscribe(Session session, SessionDetails details) {
    // Subscribe to topic to receive its events.
    CompletableFuture<Subscription> subFuture = session.subscribe("com.myapp.hello",
            this::onEvent);
    subFuture.whenComplete((subscription, throwable) -> {
        if (throwable == null) {
            // We have successfully subscribed.
            System.out.println("Subscribed to topic " + subscription.topic);
        } else {
            // Something went bad.
            throwable.printStackTrace();
        }
    });
}
private void onEvent(List<Object> args) {
    System.out.println(String.format("Got event: %s", args.get(0)));
}
public void demonstratePublish(Session session, SessionDetails details) {
    // Publish to a topic that takes a single arguments
    List<Object> args = Arrays.asList("Hello World!", 900, "UNIQUE");
    CompletableFuture<Publication> pubFuture = session.publish("com.myapp.hello", args);
    pubFuture.thenAccept(publication -> System.out.println("Published successfully"));
    // Shows we can separate out exception handling
    pubFuture.exceptionally(throwable -> {
        throwable.printStackTrace();
        return null;
    });
}
`

- C++ (https://github.com/crossbario/autobahn-cpp): You can try it with this example https://github.com/crossbario/autobahn-cpp/blob/master/examples/publisher.cpp
For me the connection doesn't work..

**Comment by gammazero** [comment]
I was able to get the Java demos working with a nexus router, and with the java authbahn client communicating with another nexus client, without making any changes to nexus.  I think the issue you are having has to do with how the autobahn examples run.

The autobahn demo runs in a docker container that expects to be bridged to their demo router container.  Notice they run their demo client container with `--link crossbar` so that it sees the "crossbar" container, and they also connect to the url `ws://crossbar:8080/ws`.  All this is visible in the Makefile.  So, here is the easiest way to configure the autobahn client to connect to nexus:

1. Configure your nexus router to use `reaml1`.  My nexusd router config looks like:
```
{
    "websocket": {
        "address": ":8080",
    },
   "router": {
        "realms": [
            {
                "uri": "realm1",
                "anonymous_auth": true
            }
        ],
    }
```
2. Create a demo target in the Makefile that does the following:
    - Uses host network stack (`--net host`)
    - Uses a URL with a resolvable hostname (`ws://localhost:8080/ws`)
  The new make target I created looks like this (mostly copied java target):
```
javanexus:
        docker run \
                -it --rm --net host \
                -v ${shell pwd}:/workspace \
                crossbario/autobahn-java:netty \
                        /bin/bash -c "gradle installDist -PbuildPlatform=netty &
& DEMO_GALLERY_OPTS="-DlogLevel=INFO" demo-gallery/build/install/demo-gallery/bi
n/demo-gallery ws://localhost:8080/ws"
```

Start the nexus server, then start the autobahn client (`make javanexus`) and it will connect just fine.  You can then connect additional nexus clients and see the publish/subscribe is working correctly.

I suspect this is the same situation with the C++ client.

**Comment by Happy-Ferret** [comment]
NVM! Was easier than I thought.

```go
// Create and run server
        s := router.NewWebsocketServer(nxr)
        s.Upgrader.CheckOrigin = check
        closer, err := s.ListenAndServe(address)
```

**Comment by gammazero** [comment]
@Happy-Ferret [This commit](https://github.com/gammazero/nexus/commit/bfe027177a53c6c3d55d670ad2c3eef5a98a83ac) adds the `WebsocketServer` method `AllowOrigins()` so that you can specify origins to match using [glob](https://golang.org/pkg/path/filepath/#Match) patterns.  Your code above could do this:
```
s := router.NewWebsocketServer(nxr)
s.AllowOrigins([]string{"*.domain.com", "*.domain.net"})
closer, err := s.ListenAndServe(address)
```

The `AllowOrigins()` function configures the websocket server with origin checking logic that allows origins based on glob matching. This handles most origin matching logic that a router needs, so is provided as a utility so that router implementers do not have to supply their own, likely similar, logic.

The websocket server still allows custom origin check logic to be assigned, by assigning a check function to `WebsocketServer.Upgrader.CheckOrigin`.
